import { Quarto, Hospede, Reserva, Produto, Pacote, ConfiguracaoSistema, Usuario, Venda } from '../tipos';

export const CONFIGURACAO_INICIAL: ConfiguracaoSistema = {
  CheckInTime: '09:00',
  CheckOutTime: '15:00',
  HotelNome: 'Hotel Fazenda Anew',
  HotelLocalizacao: 'Corguinho - Mato Grosso do Sul - Brasil',
  TelefoneHotel: '(67) 3251-1234',
  EmailHotel: 'contato@fazendaanew.com.br',
  TaxaServicoPercentual: 10,
  ModoOfflineAtivo: false,
  CriancaIdadeLimiteGratis: 5,
  CriancaIdadeLimiteMeia: 11,
  CriancaIdadeIntegral: 12,
  CriancaPorcentagemMeiaDiaria: 50,
  CriancaDescontoGratis: 100,
  CapacidadeMaximaAdultosPorQuarto: 4,
  CapacidadeMaximaCriancasPorQuarto: 3,
  FormaPagamentoPadrao: 'PIX',
  PorcentagemEntradaMinima: 30,
};

export const USUARIOS_INICIAIS: Usuario[] = [
  {
    UsuarioId: 1,
    PerfilId: 1,
    Nome: 'Amanda Morales (Admin)',
    Email: 'admin@fazendaanew.com.br',
    Perfil: 'ADMIN',
    AvatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    UsuarioId: 2,
    PerfilId: 2,
    Nome: 'Lucas Recepção',
    Email: 'recepcao@fazendaanew.com.br',
    Perfil: 'RECEPCAO',
    AvatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    UsuarioId: 3,
    PerfilId: 3,
    Nome: 'Fernanda Vendas',
    Email: 'vendas@fazendaanew.com.br',
    Perfil: 'VENDAS',
    AvatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  }
];

export const HOSPEDES_INICIAIS: Hospede[] = [
  {
    HospedeId: 1,
    NomeCompleto: 'Maria Oliveira',
    Cpf: '123.456.789-00',
    DataNascimento: '1984-05-12',
    Telefone: '(67) 99876-5432',
    WhatsApp: '(67) 99876-5432',
    Email: 'maria.oliveira@email.com',
    Cidade: 'Campo Grande',
    Estado: 'MS',
    Observacoes: 'Reserva confirmada para início de setembro.',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    HospedeId: 2,
    NomeCompleto: 'João da Silva',
    Cpf: '234.567.890-11',
    DataNascimento: '1980-03-15',
    Telefone: '(67) 99123-4567',
    WhatsApp: '(67) 99123-4567',
    Email: 'joao.silva@email.com',
    Cidade: 'Dourados',
    Estado: 'MS',
    Observacoes: 'Hospedado com a família (2 adultos e 2 crianças).',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-10T14:30:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-10T14:30:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    HospedeId: 3,
    NomeCompleto: 'Hóspede Atual',
    Cpf: '345.678.901-22',
    DataNascimento: '1988-02-18',
    Telefone: '(67) 98877-6655',
    WhatsApp: '(67) 98877-6655',
    Email: 'hospede.atual@email.com',
    Cidade: 'Cuiabá',
    Estado: 'MT',
    Observacoes: 'Check-in realizado com sucesso.',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-15T09:15:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-15T09:15:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    HospedeId: 4,
    NomeCompleto: 'Pedro Rocha',
    Cpf: '456.789.012-33',
    DataNascimento: '1976-07-30',
    Telefone: '(11) 97654-3210',
    WhatsApp: '(11) 97654-3210',
    Email: 'pedro.rocha@email.com',
    Cidade: 'São Paulo',
    Estado: 'SP',
    Observacoes: 'Chegada prevista às 14:00.',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-18T16:45:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-18T16:45:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    HospedeId: 5,
    NomeCompleto: 'Cliente Futuro',
    Cpf: '567.890.123-44',
    DataNascimento: '1995-09-04',
    Telefone: '(67) 99234-5678',
    WhatsApp: '(67) 99234-5678',
    Email: 'cliente.futuro@email.com',
    Cidade: 'Corumbá',
    Estado: 'MS',
    Observacoes: 'Reserva para a próxima semana.',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-20T11:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-20T11:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    HospedeId: 6,
    NomeCompleto: 'Grupo Agência',
    Cpf: '678.901.234-55',
    DataNascimento: '1981-12-08',
    Telefone: '(67) 99345-6789',
    WhatsApp: '(67) 99345-6789',
    Email: 'grupo.agencia@email.com',
    Cidade: 'Três Lagoas',
    Estado: 'MS',
    Observacoes: 'Aguardando check-in (Atrasado).',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-22T13:20:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-22T13:20:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    HospedeId: 7,
    NomeCompleto: 'Família Souza',
    Cpf: '789.012.345-66',
    DataNascimento: '1975-04-20',
    Telefone: '(67) 99456-7890',
    WhatsApp: '(67) 99456-7890',
    Email: 'familia.souza@email.com',
    Cidade: 'Campo Grande',
    Estado: 'MS',
    Observacoes: 'Última noite de hospedagem.',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-25T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-25T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  }
];

// EXATAMENTE 13 QUARTOS: B1, B2, B3, B4 - C2, C3, C4 - D1, D2, D3, D4, D5, D6
export const QUARTOS_INICIAIS: Quarto[] = [
  // BLOCO B (4 Quartos)
  {
    QuartoId: 1,
    Numero: 'B1',
    CodigoIdentificador: 'B1',
    Bloco: 'B',
    Categoria: 'Standard Duplo',
    CapacidadeAdultos: 2,
    CapacidadeCriancas: 1,
    ValorDiariaPadrao: 450,
    Status: 'DISPONIVEL',
    Descricao: 'Quarto aconchegante com vista para o jardim e lago.',
    Comodidades: ['Ar-condicionado', 'Frigobar', 'Wi-Fi', 'TV Smart', 'Chuveiro a gás'],
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    QuartoId: 2,
    Numero: 'B2',
    CodigoIdentificador: 'B2',
    Bloco: 'B',
    Categoria: 'Standard Casal',
    CapacidadeAdultos: 2,
    CapacidadeCriancas: 0,
    ValorDiariaPadrao: 480,
    Status: 'RESERVADO',
    Descricao: 'Cama queen size, varanda privativa e rede de descanso.',
    Comodidades: ['Ar-condicionado', 'Frigobar', 'Wi-Fi', 'TV Smart', 'Rede na varanda'],
    HospedeAtualNome: 'Maria Oliveira',
    DataEntradaAtual: '2026-09-05',
    DataSaidaAtual: '2026-09-06',
    AdultosAtual: 2,
    CriancasAtual: 0,
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    QuartoId: 3,
    Numero: 'B3',
    CodigoIdentificador: 'B3',
    Bloco: 'B',
    Categoria: 'Standard Casal',
    CapacidadeAdultos: 2,
    CapacidadeCriancas: 2,
    ValorDiariaPadrao: 480,
    Status: 'OCUPADO',
    Descricao: 'Quarto espaçoso com excelente iluminação natural.',
    Comodidades: ['Ar-condicionado', 'Frigobar', 'Wi-Fi', 'TV Smart'],
    HospedeAtualNome: 'João da Silva',
    DataEntradaAtual: '2026-08-29',
    DataSaidaAtual: '2026-09-02',
    AdultosAtual: 2,
    CriancasAtual: 2,
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    QuartoId: 4,
    Numero: 'B4',
    CodigoIdentificador: 'B4',
    Bloco: 'B',
    Categoria: 'Standard Duplo',
    CapacidadeAdultos: 2,
    CapacidadeCriancas: 1,
    ValorDiariaPadrao: 450,
    Status: 'DISPONIVEL',
    Descricao: 'Duas camas de solteiro ou uma cama king sob solicitação.',
    Comodidades: ['Ar-condicionado', 'Frigobar', 'Wi-Fi', 'Chuveiro a gás'],
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },

  // BLOCO C (3 Quartos: C2, C3, C4)
  {
    QuartoId: 5,
    Numero: 'C2',
    CodigoIdentificador: 'C2',
    Bloco: 'C',
    Categoria: 'Luxo Casal',
    CapacidadeAdultos: 2,
    CapacidadeCriancas: 1,
    ValorDiariaPadrao: 580,
    Status: 'OCUPADO',
    Descricao: 'Suíte luxo com banheira de hidromassagem e vista para a mata.',
    Comodidades: ['Hidromassagem', 'Ar-condicionado Split', 'Frigobar', 'Cafeteira Nespresso', 'Wi-Fi'],
    HospedeAtualNome: 'Hóspede Atual',
    DataEntradaAtual: '2026-08-28',
    DataSaidaAtual: '2026-09-01',
    AdultosAtual: 2,
    CriancasAtual: 0,
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    QuartoId: 6,
    Numero: 'C3',
    CodigoIdentificador: 'C3',
    Bloco: 'C',
    Categoria: 'Luxo Duplo',
    CapacidadeAdultos: 3,
    CapacidadeCriancas: 1,
    ValorDiariaPadrao: 620,
    Status: 'AGUARDANDO_CHECKIN',
    Descricao: 'Quarto amplo com acabamento rústico sofisticado.',
    Comodidades: ['Ar-condicionado Split', 'Frigobar', 'Wi-Fi', 'TV 50 pol', 'Secador de cabelo'],
    HospedeAtualNome: 'Pedro Rocha',
    DataEntradaAtual: '2026-08-31',
    DataSaidaAtual: '2026-09-03',
    AdultosAtual: 2,
    CriancasAtual: 0,
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    QuartoId: 7,
    Numero: 'C4',
    CodigoIdentificador: 'C4',
    Bloco: 'C',
    Categoria: 'Chalé Master',
    CapacidadeAdultos: 4,
    CapacidadeCriancas: 2,
    ValorDiariaPadrao: 750,
    Status: 'DISPONIVEL',
    Descricao: 'Chalé exclusivo independente com 2 ambientes e lareira ecológica.',
    Comodidades: ['Lareira ecológica', 'Varanda com deck', 'Ar-condicionado', 'Frigobar grande', 'Cafeteira', 'Wi-Fi'],
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },

  // BLOCO D (6 Quartos: D1, D2, D3, D4, D5, D6)
  {
    QuartoId: 8,
    Numero: 'D1',
    CodigoIdentificador: 'D1',
    Bloco: 'D',
    Categoria: 'Standard Triplo',
    CapacidadeAdultos: 3,
    CapacidadeCriancas: 1,
    ValorDiariaPadrao: 520,
    Status: 'RESERVADO',
    Descricao: 'Excelente opção para famílias e pequenos grupos.',
    Comodidades: ['Ar-condicionado', 'Frigobar', 'Wi-Fi', 'TV Smart'],
    HospedeAtualNome: 'Cliente Futuro',
    DataEntradaAtual: '2026-09-07',
    DataSaidaAtual: '2026-09-10',
    AdultosAtual: 3,
    CriancasAtual: 1,
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    QuartoId: 9,
    Numero: 'D2',
    CodigoIdentificador: 'D2',
    Bloco: 'D',
    Categoria: 'Standard Triplo',
    CapacidadeAdultos: 3,
    CapacidadeCriancas: 1,
    ValorDiariaPadrao: 520,
    Status: 'AGUARDANDO_CHECKIN',
    Descricao: 'Próximo à piscina e à área de convivência.',
    Comodidades: ['Ar-condicionado', 'Frigobar', 'Wi-Fi', 'Chuveiro pressurizado'],
    HospedeAtualNome: 'Grupo Agência',
    DataEntradaAtual: '2026-08-31',
    DataSaidaAtual: '2026-09-04',
    AdultosAtual: 4,
    CriancasAtual: 0,
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    QuartoId: 10,
    Numero: 'D3',
    CodigoIdentificador: 'D3',
    Bloco: 'D',
    Categoria: 'Luxo Casal',
    CapacidadeAdultos: 2,
    CapacidadeCriancas: 1,
    ValorDiariaPadrao: 600,
    Status: 'DISPONIVEL',
    Descricao: 'Quarto silencioso com vista privilegiada para o pôr do sol.',
    Comodidades: ['Ar-condicionado Split', 'Frigobar', 'Wi-Fi', 'Cama King Size', 'Deck privativo'],
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    QuartoId: 11,
    Numero: 'D4',
    CodigoIdentificador: 'D4',
    Bloco: 'D',
    Categoria: 'Chalé Família',
    CapacidadeAdultos: 5,
    CapacidadeCriancas: 2,
    ValorDiariaPadrao: 850,
    Status: 'OCUPADO',
    Descricao: 'Grande chalé com 2 quartos separados e sala de convivência.',
    Comodidades: ['2 Quartos', 'Sala de estar', 'Cozinha compacta', 'Varanda panorâmica', 'Wi-Fi', '2 Ar-condicionados'],
    HospedeAtualNome: 'Família Souza',
    DataEntradaAtual: '2026-08-28',
    DataSaidaAtual: '2026-09-01',
    AdultosAtual: 4,
    CriancasAtual: 2,
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    QuartoId: 12,
    Numero: 'D5',
    CodigoIdentificador: 'D5',
    Bloco: 'D',
    Categoria: 'Vila Premium',
    CapacidadeAdultos: 4,
    CapacidadeCriancas: 2,
    ValorDiariaPadrao: 980,
    Status: 'MANUTENCAO',
    Descricao: 'Vila privativa com piscina aquecida e área de churrasqueira.',
    MotivoBloqueio: 'Ar condicionado',
    Comodidades: ['Piscina privativa aquecida', 'Área gourmet', '2 Suítes', 'Wi-Fi fibra'],
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    QuartoId: 13,
    Numero: 'D6',
    CodigoIdentificador: 'D6',
    Bloco: 'D',
    Categoria: 'Chalé Master',
    CapacidadeAdultos: 4,
    CapacidadeCriancas: 2,
    ValorDiariaPadrao: 790,
    Status: 'DISPONIVEL',
    Descricao: 'Chalé moderno com vista para os morros e área verde.',
    Comodidades: ['Ar-condicionado', 'Varanda panorâmica', 'Frigobar', 'Wi-Fi', 'TV 4K'],
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  }
];

export const PACOTES_INICIAIS: Pacote[] = [
  {
    PacoteId: 1,
    Nome: 'Pacote Final de Semana Fazenda',
    Descricao: 'Check-in sexta-feira às 15:00 e check-out domingo às 17:00 com pensão completa inclusa.',
    Valor: 1450,
    AdultosInclusos: 2,
    CriancasInclusas: 1,
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    PacoteId: 2,
    Nome: 'Pacote Família Pantaneira',
    Descricao: '3 diárias para família com cavalgada, pesque-solte e almoço na fazenda.',
    Valor: 2890,
    AdultosInclusos: 4,
    CriancasInclusas: 2,
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    PacoteId: 3,
    Nome: 'Pacote Romântico Chalé Master',
    Descricao: '2 diárias com espumante de boas-vindas, tábua de queijos regionais e café na varanda.',
    Valor: 1850,
    AdultosInclusos: 2,
    CriancasInclusas: 0,
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  }
];

export const PRODUTOS_INICIAIS: Produto[] = [
  {
    ProdutoId: 1,
    Nome: 'Água Mineral Anew 500ml',
    Descricao: 'Água mineral da fonte natural da fazenda.',
    Categoria: 'Bebidas',
    Preco: 6.00,
    Estoque: 142,
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    ProdutoId: 2,
    Nome: 'Ovo Caipira da Fazenda (Dúzia)',
    Descricao: 'Ovos caipiras frescos colhidos no galinheiro da fazenda.',
    Categoria: 'Produtos da Fazenda',
    Preco: 18.00,
    Estoque: 35,
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    ProdutoId: 3,
    Nome: 'Doce de Leite Artesanal Anew 400g',
    Descricao: 'Produção própria no tacho de cobre com leite fresco.',
    Categoria: 'Produtos da Fazenda',
    Preco: 28.00,
    Estoque: 24,
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    ProdutoId: 4,
    Nome: 'Mel Silvestre Puro 500g',
    Descricao: 'Mel puro de florada nativa do cerrado de Corguinho.',
    Categoria: 'Produtos da Fazenda',
    Preco: 35.00,
    Estoque: 18,
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    ProdutoId: 5,
    Nome: 'Camiseta Oficial Hotel Fazenda Anew',
    Descricao: 'Algodão premium 100% com a logo oficial do Tucano bordada.',
    Categoria: 'Vestuário / Lembranças',
    Preco: 85.00,
    Estoque: 15,
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    ProdutoId: 6,
    Nome: 'Cerveja Artesanal Pantaneira 600ml',
    Descricao: 'Cerveja artesanal local de trigo e malte selecionado.',
    Categoria: 'Bebidas',
    Preco: 22.00,
    Estoque: 40,
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-01T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-01T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  }
];

export const RESERVAS_INICIAIS: Reserva[] = [
  {
    ReservaId: 49281,
    Codigo: '#49281',
    HospedeId: 1,
    HospedeNome: 'Maria Oliveira',
    HospedeTelefone: '(67) 99876-5432',
    HospedeEmail: 'maria.oliveira@email.com',
    QuartoId: 2,
    QuartoNumero: 'B2',
    QuartoCodigo: 'B2',
    QuartoCategoria: 'Standard Casal',
    Adultos: 2,
    Criancas: 0,
    DataEntrada: '2026-09-05',
    DataSaida: '2026-09-06',
    HorarioPrevistoChegada: '14:00',
    HorarioPrevistoSaida: '12:00',
    TipoAtendimento: 'HOSPEDAGEM',
    PacoteId: 1,
    PacoteNome: 'Pacote Final de Semana Fazenda',
    Status: 'CONFIRMADA',
    ValorTotal: 960.00,
    ValorPago: 960.00,
    Saldo: 0.00,
    StatusPagamento: 'PAGO',
    FormaPagamento: 'PIX',
    Observacoes: 'Reserva para 05/09 a 06/09.',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-20T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-20T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    ReservaId: 49282,
    Codigo: '#49282',
    HospedeId: 2,
    HospedeNome: 'João da Silva',
    HospedeTelefone: '(67) 99123-4567',
    HospedeEmail: 'joao.silva@email.com',
    QuartoId: 3,
    QuartoNumero: 'B3',
    QuartoCodigo: 'B3',
    QuartoCategoria: 'Standard Casal',
    Adultos: 2,
    Criancas: 2,
    DataEntrada: '2026-08-29',
    DataSaida: '2026-09-02',
    TipoAtendimento: 'HOSPEDAGEM',
    Status: 'HOSPEDADO',
    ValorTotal: 1920.00,
    ValorPago: 1920.00,
    Saldo: 0.00,
    StatusPagamento: 'PAGO',
    FormaPagamento: 'CARTAO_CREDITO',
    CheckinRealizadoEm: '2026-08-29T10:30:00Z',
    CheckinUsuario: 'Lucas Recepção',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-15T16:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-15T16:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    ReservaId: 49283,
    Codigo: '#49283',
    HospedeId: 3,
    HospedeNome: 'Hóspede Atual',
    HospedeTelefone: '(67) 98877-6655',
    HospedeEmail: 'hospede.atual@email.com',
    QuartoId: 5,
    QuartoNumero: 'C2',
    QuartoCodigo: 'C2',
    QuartoCategoria: 'Luxo Casal',
    Adultos: 2,
    Criancas: 0,
    DataEntrada: '2026-08-28',
    DataSaida: '2026-09-01',
    TipoAtendimento: 'HOSPEDAGEM',
    Status: 'HOSPEDADO',
    ValorTotal: 1740.00,
    ValorPago: 1740.00,
    Saldo: 0.00,
    StatusPagamento: 'PAGO',
    FormaPagamento: 'PIX',
    CheckinRealizadoEm: '2026-08-28T14:00:00Z',
    CheckinUsuario: 'Amanda Morales (Admin)',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-18T10:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-18T10:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    ReservaId: 49284,
    Codigo: '#49284',
    HospedeId: 4,
    HospedeNome: 'Pedro Rocha',
    HospedeTelefone: '(11) 97654-3210',
    HospedeEmail: 'pedro.rocha@email.com',
    QuartoId: 6,
    QuartoNumero: 'C3',
    QuartoCodigo: 'C3',
    QuartoCategoria: 'Luxo Duplo',
    Adultos: 2,
    Criancas: 0,
    DataEntrada: '2026-08-31',
    DataSaida: '2026-09-03',
    HorarioPrevistoChegada: '14:00',
    HorarioPrevistoSaida: '12:00',
    TipoAtendimento: 'HOSPEDAGEM',
    Status: 'AGUARDANDO_CHECKIN',
    ValorTotal: 1860.00,
    ValorPago: 1860.00,
    Saldo: 0.00,
    StatusPagamento: 'PAGO',
    FormaPagamento: 'PIX',
    Observacoes: 'Previsto: 14:00.',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-25T09:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-25T09:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    ReservaId: 49285,
    Codigo: '#49285',
    HospedeId: 5,
    HospedeNome: 'Cliente Futuro',
    HospedeTelefone: '(67) 99234-5678',
    HospedeEmail: 'cliente.futuro@email.com',
    QuartoId: 8,
    QuartoNumero: 'D1',
    QuartoCodigo: 'D1',
    QuartoCategoria: 'Standard Triplo',
    Adultos: 3,
    Criancas: 1,
    DataEntrada: '2026-09-07',
    DataSaida: '2026-09-10',
    HorarioPrevistoChegada: '15:00',
    TipoAtendimento: 'HOSPEDAGEM',
    Status: 'CONFIRMADA',
    ValorTotal: 1560.00,
    ValorPago: 500.00,
    Saldo: 1060.00,
    StatusPagamento: 'PARCIAL',
    FormaPagamento: 'PIX',
    Observacoes: 'Próxima semana.',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-28T09:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-28T09:00:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    ReservaId: 49286,
    Codigo: '#49286',
    HospedeId: 6,
    HospedeNome: 'Grupo Agência',
    HospedeTelefone: '(67) 99345-6789',
    HospedeEmail: 'grupo.agencia@email.com',
    QuartoId: 9,
    QuartoNumero: 'D2',
    QuartoCodigo: 'D2',
    QuartoCategoria: 'Standard Triplo',
    Adultos: 4,
    Criancas: 0,
    DataEntrada: '2026-08-31',
    DataSaida: '2026-09-04',
    HorarioPrevistoChegada: '16:00',
    TipoAtendimento: 'HOSPEDAGEM',
    Status: 'AGUARDANDO_CHECKIN',
    ValorTotal: 2080.00,
    ValorPago: 1040.00,
    Saldo: 1040.00,
    StatusPagamento: 'PARCIAL',
    FormaPagamento: 'CARTAO_CREDITO',
    Observacoes: 'Atrasado.',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-22T14:30:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-22T14:30:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    ReservaId: 49287,
    Codigo: '#49287',
    HospedeId: 7,
    HospedeNome: 'Família Souza',
    HospedeTelefone: '(67) 99456-7890',
    HospedeEmail: 'familia.souza@email.com',
    QuartoId: 11,
    QuartoNumero: 'D4',
    QuartoCodigo: 'D4',
    QuartoCategoria: 'Chalé Família',
    Adultos: 4,
    Criancas: 2,
    DataEntrada: '2026-08-28',
    DataSaida: '2026-09-01',
    HorarioPrevistoSaida: '14:00',
    TipoAtendimento: 'HOSPEDAGEM',
    Status: 'HOSPEDADO',
    ValorTotal: 3400.00,
    ValorPago: 3400.00,
    Saldo: 0.00,
    StatusPagamento: 'PAGO',
    FormaPagamento: 'PIX',
    Observacoes: 'Última noite.',
    CheckinRealizadoEm: '2026-08-28T11:00:00Z',
    CheckinUsuario: 'Amanda Morales (Admin)',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-19T11:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-19T11:00:00Z',
    NaturezaOperacao: 'INSERT',
  }
];

export const VENDAS_INICIAIS: Venda[] = [
  {
    VendaId: 101,
    Codigo: 'VND-00101',
    Tipo: 'LOJA',
    HospedeNome: 'Carlos Silva',
    Itens: [
      {
        ItemVendaId: 1,
        VendaId: 101,
        ProdutoId: 1,
        ProdutoNome: 'Água Mineral Anew 500ml',
        Quantidade: 4,
        PrecoUnitario: 6.00,
        Subtotal: 24.00,
        Ativo: true,
      },
      {
        ItemVendaId: 2,
        VendaId: 101,
        ProdutoId: 3,
        ProdutoNome: 'Doce de Leite Artesanal Anew 400g',
        Quantidade: 2,
        PrecoUnitario: 28.00,
        Subtotal: 56.00,
        Ativo: true,
      }
    ],
    ValorTotal: 80.00,
    FormaPagamento: 'PIX',
    StatusPagamento: 'PAGO',
    DataHora: '2026-08-31T10:15:00Z',
    UsuarioResponsavel: 'Lucas Recepção',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-31T10:15:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-31T10:15:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    VendaId: 102,
    Codigo: 'VND-00102',
    Tipo: 'LOJA',
    HospedeNome: 'Roberto Almeida',
    Itens: [
      {
        ItemVendaId: 3,
        VendaId: 102,
        ProdutoId: 2,
        ProdutoNome: 'Ovo Caipira da Fazenda (Dúzia)',
        Quantidade: 3,
        PrecoUnitario: 18.00,
        Subtotal: 54.00,
        Ativo: true,
      },
      {
        ItemVendaId: 4,
        VendaId: 102,
        ProdutoId: 4,
        ProdutoNome: 'Mel Silvestre Puro 500g',
        Quantidade: 1,
        PrecoUnitario: 35.00,
        Subtotal: 35.00,
        Ativo: true,
      }
    ],
    ValorTotal: 89.00,
    FormaPagamento: 'CARTAO_CREDITO',
    StatusPagamento: 'PAGO',
    DataHora: '2026-08-31T11:45:00Z',
    UsuarioResponsavel: 'Amanda Morales (Admin)',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-31T11:45:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-31T11:45:00Z',
    NaturezaOperacao: 'INSERT',
  },
  {
    VendaId: 103,
    Codigo: 'VND-00103',
    Tipo: 'DAY_USE',
    HospedeNome: 'Família Souza (Visitantes Day Use)',
    Itens: [
      {
        ItemVendaId: 5,
        VendaId: 103,
        ProdutoId: 101,
        ProdutoNome: 'Ingresso Day Use Fazenda Anew (Adulto)',
        Quantidade: 3,
        PrecoUnitario: 120.00,
        Subtotal: 360.00,
        Ativo: true,
      },
      {
        ItemVendaId: 6,
        VendaId: 103,
        ProdutoId: 102,
        ProdutoNome: 'Ingresso Day Use Fazenda Anew (Criança)',
        Quantidade: 2,
        PrecoUnitario: 60.00,
        Subtotal: 120.00,
        Ativo: true,
      }
    ],
    ValorTotal: 480.00,
    FormaPagamento: 'PIX',
    StatusPagamento: 'PAGO',
    DataHora: '2026-08-31T09:00:00Z',
    UsuarioResponsavel: 'Fernanda Vendas',
    Ativo: true,
    UsuarioInclusao: 'SISTEMA',
    DataInclusao: '2026-08-31T09:00:00Z',
    UsuarioOperacao: 'SISTEMA',
    DataOperacao: '2026-08-31T09:00:00Z',
    NaturezaOperacao: 'INSERT',
  }
];
