-- Modelo financeiro: pagamentos separados e consumos vinculados a reservas.
-- Execute após validar os nomes das constraints no banco existente.

alter table public.pagamento
  add column if not exists tipolancamento text;

update public.pagamento
set tipolancamento = 'SINAL_RESERVA'
where tipolancamento is null;

alter table public.pagamento
  alter column tipolancamento set default 'FECHAMENTO_GERAL';

alter table public.pagamento
  add constraint pagamento_tipolancamento_check
  check (tipolancamento in ('SINAL_RESERVA', 'SALDO_DIARIAS', 'CONSUMO_EXTRA', 'FECHAMENTO_GERAL'));

create table if not exists public.consumo_extra (
  consumoid integer generated by default as identity primary key,
  reservaid integer not null references public.reserva (reservaid),
  produtoid integer references public.produto (produtoid),
  quantidade numeric(12, 3) not null check (quantidade > 0),
  valorunitario numeric(12, 2) not null check (valorunitario >= 0),
  valortotal numeric(12, 2) generated always as (quantidade * valorunitario) stored,
  dataconsumo timestamptz not null default now(),
  categoria text not null,
  descricao text,
  ativo boolean not null default true,
  usuarioinclusao integer,
  datainclusao timestamptz not null default now()
);

create index if not exists consumo_extra_reservaid_idx
  on public.consumo_extra (reservaid)
  where ativo = true;

alter table public.reserva
  add column if not exists totalconsumos numeric(12, 2) not null default 0,
  add column if not exists saldodevedor numeric(12, 2) not null default 0;
