-- Cadastro FNRH preenchido pelo cliente.
-- Fluxo:
-- 1. Cliente preenche: AGUARDANDO_PAGAMENTO.
-- 2. Administrador confirma o sinal: LIBERADA_PARA_RESERVA e importa o titular para hospede.
-- 3. Atendente cria a reserva no mapa: RESERVA_CRIADA e grava reservaid.
-- 4. Administrador pode cancelar: CANCELADA.
--
-- Execute este arquivo no Supabase SQL Editor.

-- pgcrypto é opcional. O exemplo de token no final usa funções nativas.

-- ============================================================================
-- Campos definitivos do titular em public.hospede
-- Esses dados são copiados do cadastro_fnrh quando o pagamento for confirmado.
-- ============================================================================
alter table public.hospede
  add column if not exists rg text,
  add column if not exists passaporte text,
  add column if not exists nacionalidade text default 'Brasileira',
  add column if not exists sexo text,
  add column if not exists endereco text,
  add column if not exists cep text,
  add column if not exists profissao text,
  add column if not exists proximodestino text,
  add column if not exists ultimaprocedencia text,
  add column if not exists cpfresponsavelmenor text,
  add column if not exists alergias_restricoes text,
  add column if not exists solicitacoes_especiais text,
  add column if not exists declaracao_aceita boolean not null default false,
  add column if not exists data_declaracao timestamptz,
  add column if not exists assinatura_url text;

alter table public.hospede
  drop constraint if exists hospede_sexo_check;

alter table public.hospede
  add constraint hospede_sexo_check
  check (sexo is null or sexo in ('M', 'F'));

create table if not exists public.cadastro_fnrh (
  cadastroid bigint generated by default as identity primary key,

  -- Controle do fluxo
  status text not null default 'AGUARDANDO_PAGAMENTO'
    check (status in (
      'AGUARDANDO_PAGAMENTO',
      'LIBERADA_PARA_RESERVA',
      'RESERVA_CRIADA',
      'CANCELADA'
    )),
  token_acesso text not null unique,
  token_expira_em timestamptz not null default (now() + interval '7 days'),

  -- Ligações feitas pelo sistema
  hospedeid integer null references public.hospede(hospedeid),
  reservaid integer null references public.reserva(reservaid),

  -- Dados do hóspede titular
  nomecompleto text,
  cpf text,
  rg text,
  passaporte text,
  datanascimento date,
  nacionalidade text default 'Brasileira',
  sexo text check (sexo is null or sexo in ('M', 'F')),
  telefone text,
  email text,
  endereco text,
  cidade text,
  estado text,
  cep text,
  profissao text,
  proximodestino text,
  ultimaprocedencia text,
  cpfresponsavelmenor text,

  -- Dados informados para a hospedagem
  dataentrada date,
  horarioprevistochegada time,
  datasaida date,
  horarioprevistasaida time,
  motivoviagem text,
  transporte text,
  placa text,
  modelocor text,
  numerohospedes integer not null default 1 check (numerohospedes > 0),
  adultos integer not null default 1 check (adultos >= 0),
  criancas integer not null default 0 check (criancas >= 0),

  -- Pagamento conferido manualmente pelo administrador
  forma_pagamento text check (forma_pagamento is null or forma_pagamento in ('PIX', 'VOUCHER')),
  valor_sinal numeric(12,2) not null default 0 check (valor_sinal >= 0),
  comprovante_url text,
  pagamento_confirmado_em timestamptz,
  pagamento_confirmado_por integer references public.usuario(usuarioid),

  -- Observações e declaração da FNRH
  alergias_restricoes text,
  solicitacoes_especiais text,
  declaracao_aceita boolean not null default false,
  data_declaracao timestamptz,
  assinatura_url text,

  -- Auditoria básica
  datainclusao timestamptz not null default now(),
  dataoperacao timestamptz not null default now(),
  usuariooperacao integer references public.usuario(usuarioid),
  naturezaoperacao text not null default 'INSERT'
);

alter table public.cadastro_fnrh
  alter column nomecompleto drop not null,
  alter column cpf drop not null,
  alter column telefone drop not null;

create index if not exists cadastro_fnrh_status_idx
  on public.cadastro_fnrh(status);

create index if not exists cadastro_fnrh_cpf_idx
  on public.cadastro_fnrh(cpf);

create index if not exists cadastro_fnrh_hospede_idx
  on public.cadastro_fnrh(hospedeid);

create index if not exists cadastro_fnrh_reserva_idx
  on public.cadastro_fnrh(reservaid);

create table if not exists public.cadastro_fnrh_acompanhante (
  acompanhanteid bigint generated by default as identity primary key,
  cadastroid bigint not null references public.cadastro_fnrh(cadastroid) on delete cascade,
  reservaid integer null references public.reserva(reservaid),

  nomecompleto text not null,
  documento text,
  datanascimento date,
  menoridade boolean not null default false,
  cpfresponsavel text,
  autorizacao_url text,
  autorizacao_validada boolean not null default false,
  observacoes text,
  datainclusao timestamptz not null default now()
);

create index if not exists cadastro_fnrh_acompanhante_cadastro_idx
  on public.cadastro_fnrh_acompanhante(cadastroid);

create index if not exists cadastro_fnrh_acompanhante_reserva_idx
  on public.cadastro_fnrh_acompanhante(reservaid);

-- ============================================================================
-- Acompanhantes definitivos
-- Os registros são copiados para esta tabela quando o pagamento for confirmado.
-- Ela não depende da tabela temporária cadastro_fnrh_acompanhante.
-- ============================================================================
create table if not exists public.acompanhante (
  acompanhanteid bigint generated by default as identity primary key,
  cadastroid bigint null,
  reservaid integer null references public.reserva(reservaid),

  nomecompleto text not null,
  documento text,
  datanascimento date,
  menoridade boolean not null default false,
  cpfresponsavel text,
  autorizacao_url text,
  autorizacao_validada boolean not null default false,
  observacoes text,

  ativo boolean not null default true,
  datainclusao timestamptz not null default now(),
  dataoperacao timestamptz not null default now(),
  usuariooperacao integer references public.usuario(usuarioid),
  naturezaoperacao text not null default 'INSERT'
);

create index if not exists acompanhante_reserva_idx
  on public.acompanhante(reservaid);

create index if not exists acompanhante_cadastro_idx
  on public.acompanhante(cadastroid);

-- ============================================================================
-- Acesso público seguro por token
-- O formulário do cliente usa estas funções, nunca SELECT/UPDATE direto.
-- ============================================================================
create or replace function public.obter_cadastro_fnrh_por_token(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  cadastro jsonb;
  acompanhantes jsonb;
begin
  select to_jsonb(c)
    into cadastro
    from public.cadastro_fnrh c
   where c.token_acesso = p_token
     and c.token_expira_em > now()
     and c.status in ('AGUARDANDO_PAGAMENTO', 'LIBERADA_PARA_RESERVA');

  if cadastro is null then
    raise exception 'Cadastro não encontrado ou link expirado';
  end if;

  select coalesce(jsonb_agg(to_jsonb(a) order by a.acompanhanteid), '[]'::jsonb)
    into acompanhantes
    from public.cadastro_fnrh_acompanhante a
   where a.cadastroid = (cadastro->>'cadastroid')::bigint;

  return jsonb_build_object(
    'cadastro', cadastro - 'token_acesso' - 'token_expira_em' - 'pagamento_confirmado_por',
    'acompanhantes', acompanhantes
  );
end;
$$;

create or replace function public.salvar_cadastro_fnrh_por_token(
  p_token text,
  p_dados jsonb,
  p_acompanhantes jsonb default '[]'::jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  cadastro_id bigint;
begin
  select cadastroid into cadastro_id
    from public.cadastro_fnrh
   where token_acesso = p_token
     and token_expira_em > now()
     and status = 'AGUARDANDO_PAGAMENTO';

  if cadastro_id is null then
    raise exception 'Cadastro não encontrado, já liberado ou link expirado';
  end if;

  update public.cadastro_fnrh
     set nomecompleto = coalesce(nullif(trim(p_dados->>'nomecompleto'), ''), nomecompleto),
         cpf = coalesce(nullif(trim(p_dados->>'cpf'), ''), cpf),
         rg = nullif(trim(p_dados->>'rg'), ''),
         passaporte = nullif(trim(p_dados->>'passaporte'), ''),
         datanascimento = nullif(p_dados->>'datanascimento', '')::date,
         nacionalidade = nullif(trim(p_dados->>'nacionalidade'), ''),
         sexo = nullif(p_dados->>'sexo', ''),
         telefone = coalesce(nullif(trim(p_dados->>'telefone'), ''), telefone),
         email = nullif(trim(p_dados->>'email'), ''),
         endereco = nullif(trim(p_dados->>'endereco'), ''),
         cidade = nullif(trim(p_dados->>'cidade'), ''),
         estado = nullif(trim(p_dados->>'estado'), ''),
         cep = nullif(trim(p_dados->>'cep'), ''),
         profissao = nullif(trim(p_dados->>'profissao'), ''),
         proximodestino = nullif(trim(p_dados->>'proximodestino'), ''),
         ultimaprocedencia = nullif(trim(p_dados->>'ultimaprocedencia'), ''),
         cpfresponsavelmenor = nullif(trim(p_dados->>'cpfresponsavelmenor'), ''),
         dataentrada = nullif(p_dados->>'dataentrada', '')::date,
         horarioprevistochegada = nullif(p_dados->>'horarioprevistochegada', '')::time,
         datasaida = nullif(p_dados->>'datasaida', '')::date,
         horarioprevistasaida = nullif(p_dados->>'horarioprevistasaida', '')::time,
         motivoviagem = nullif(trim(p_dados->>'motivoviagem'), ''),
         transporte = nullif(trim(p_dados->>'transporte'), ''),
         placa = nullif(trim(p_dados->>'placa'), ''),
         modelocor = nullif(trim(p_dados->>'modelocor'), ''),
         numerohospedes = greatest(1, coalesce((p_dados->>'numerohospedes')::integer, numerohospedes)),
         adultos = greatest(0, coalesce((p_dados->>'adultos')::integer, adultos)),
         criancas = greatest(0, coalesce((p_dados->>'criancas')::integer, criancas)),
         forma_pagamento = nullif(p_dados->>'forma_pagamento', ''),
         alergias_restricoes = nullif(trim(p_dados->>'alergias_restricoes'), ''),
         solicitacoes_especiais = nullif(trim(p_dados->>'solicitacoes_especiais'), ''),
         declaracao_aceita = coalesce((p_dados->>'declaracao_aceita')::boolean, false),
         data_declaracao = case when coalesce((p_dados->>'declaracao_aceita')::boolean, false) then now() else data_declaracao end,
         dataoperacao = now(), naturezaoperacao = 'UPDATE'
   where cadastroid = cadastro_id;

  delete from public.cadastro_fnrh_acompanhante where cadastroid = cadastro_id;
  insert into public.cadastro_fnrh_acompanhante (cadastroid, nomecompleto, documento, datanascimento, menoridade, cpfresponsavel, observacoes)
  select cadastro_id, item->>'nomecompleto', nullif(item->>'documento', ''), nullif(item->>'datanascimento', '')::date,
         coalesce((item->>'menoridade')::boolean, false), nullif(item->>'cpfresponsavel', ''), nullif(item->>'observacoes', '')
    from jsonb_array_elements(coalesce(p_acompanhantes, '[]'::jsonb)) item
   where nullif(trim(item->>'nomecompleto'), '') is not null;

  return jsonb_build_object('cadastroid', cadastro_id, 'status', 'AGUARDANDO_PAGAMENTO');
end;
$$;

revoke all on function public.obter_cadastro_fnrh_por_token(text) from public;
revoke all on function public.salvar_cadastro_fnrh_por_token(text, jsonb, jsonb) from public;
grant execute on function public.obter_cadastro_fnrh_por_token(text) to anon, authenticated;
grant execute on function public.salvar_cadastro_fnrh_por_token(text, jsonb, jsonb) to anon, authenticated;

-- Regras da aplicação:
--
-- Confirmação manual pelo administrador:
-- update public.cadastro_fnrh
-- set status = 'LIBERADA_PARA_RESERVA',
--     pagamento_confirmado_em = now(),
--     pagamento_confirmado_por = :usuario_admin,
--     dataoperacao = now(),
--     naturezaoperacao = 'UPDATE'
-- where cadastroid = :cadastroid
--   and status = 'AGUARDANDO_PAGAMENTO';
--
-- Nesse mesmo fluxo, a aplicação deve criar/atualizar o titular em public.hospede
-- e salvar o hospedeid no cadastro_fnrh.
-- Também deve importar os acompanhantes:
-- insert into public.acompanhante (
--   cadastroid, nomecompleto, documento, datanascimento, menoridade,
--   cpfresponsavel, autorizacao_url, autorizacao_validada, observacoes,
--   usuariooperacao
-- )
-- select cadastroid, nomecompleto, documento, datanascimento, menoridade,
--        cpfresponsavel, autorizacao_url, autorizacao_validada, observacoes,
--        :usuario_admin
-- from public.cadastro_fnrh_acompanhante
-- where cadastroid = :cadastroid;
-- Também deve copiar para hospede:
-- rg, passaporte, datanascimento, nacionalidade, sexo, telefone, email,
-- endereco, cidade, estado, cep, profissao, proximodestino,
-- ultimaprocedencia, cpfresponsavelmenor, alergias_restricoes,
-- solicitacoes_especiais, declaracao_aceita, data_declaracao e assinatura_url.
--
-- Depois que a atendente criar a reserva, os pagamentos e os dados da reserva
-- seguem o fluxo normal já existente no sistema. Depois disso, os acompanhantes
-- importados devem receber o reservaid:
-- update public.acompanhante
-- set reservaid = :reservaid, dataoperacao = now(), naturezaoperacao = 'UPDATE'
-- where cadastroid = :cadastroid and reservaid is null;
-- update public.cadastro_fnrh
-- set status = 'RESERVA_CRIADA', reservaid = :reservaid,
--     dataoperacao = now(), naturezaoperacao = 'UPDATE'
-- where cadastroid = :cadastroid
--   and status = 'LIBERADA_PARA_RESERVA';
--
-- Para cancelar:
-- update public.cadastro_fnrh
-- set status = 'CANCELADA', dataoperacao = now(), naturezaoperacao = 'UPDATE'
-- where cadastroid = :cadastroid
--   and status in ('AGUARDANDO_PAGAMENTO', 'LIBERADA_PARA_RESERVA');
--
-- O cliente deve receber somente um link/token para preencher o próprio cadastro.
-- Não conceda acesso geral às tabelas cadastro_fnrh ou hospede para o cliente.
--
-- Para criar um link inicial pelo SQL Editor:
-- insert into public.cadastro_fnrh (token_acesso)
-- values (md5(random()::text || clock_timestamp()::text || txid_current()::text))
-- returning cadastroid, token_acesso,
--   'https://SEU-DOMINIO/fnrh/' || token_acesso as link_publico;
