-- Cadastro FNRH preenchido pelo cliente.
-- Fluxo:
-- 1. Cliente preenche: AGUARDANDO_PAGAMENTO.
-- 2. Administrador confirma o sinal: LIBERADA_PARA_RESERVA e importa o titular para hospede.
-- 3. Atendente cria a reserva no mapa: RESERVA_CRIADA e grava reservaid.
-- 4. Administrador pode cancelar: CANCELADA.
--
-- Execute este arquivo no Supabase SQL Editor.

-- ============================================================================
-- Campos definitivos do titular em public.hospede
-- Esses dados são copiados do cadastro_fnrh quando o pagamento for confirmado.
-- ============================================================================
alter table public.hospede
  add column if not exists rg text,
  add column if not exists passaporte text,
  add column if not exists nacionalidade text default 'Brasileira',
  add column if not exists sexo text,
  add column if not exists endereco text,
  add column if not exists cep text,
  add column if not exists profissao text,
  add column if not exists proximodestino text,
  add column if not exists ultimaprocedencia text,
  add column if not exists cpfresponsavelmenor text,
  add column if not exists alergias_restricoes text,
  add column if not exists solicitacoes_especiais text,
  add column if not exists declaracao_aceita boolean not null default false,
  add column if not exists data_declaracao timestamptz,
  add column if not exists assinatura_url text;

alter table public.hospede
  drop constraint if exists hospede_sexo_check;

alter table public.hospede
  add constraint hospede_sexo_check
  check (sexo is null or sexo in ('M', 'F'));

create table if not exists public.cadastro_fnrh (
  cadastroid bigint generated by default as identity primary key,

  -- Controle do fluxo
  status text not null default 'AGUARDANDO_PAGAMENTO'
    check (status in (
      'AGUARDANDO_PAGAMENTO',
      'LIBERADA_PARA_RESERVA',
      'RESERVA_CRIADA',
      'CANCELADA'
    )),
  token_acesso text not null unique,
  token_expira_em timestamptz not null default (now() + interval '7 days'),

  -- Ligações feitas pelo sistema
  hospedeid integer null references public.hospede(hospedeid),
  reservaid integer null references public.reserva(reservaid),

  -- Dados do hóspede titular
  nomecompleto text not null,
  cpf text not null,
  rg text,
  passaporte text,
  datanascimento date,
  nacionalidade text default 'Brasileira',
  sexo text check (sexo is null or sexo in ('M', 'F')),
  telefone text not null,
  email text,
  endereco text,
  cidade text,
  estado text,
  cep text,
  profissao text,
  proximodestino text,
  ultimaprocedencia text,
  cpfresponsavelmenor text,

  -- Dados informados para a hospedagem
  dataentrada date,
  horarioprevistochegada time,
  datasaida date,
  horarioprevistasaida time,
  motivoviagem text,
  transporte text,
  placa text,
  modelocor text,
  numerohospedes integer not null default 1 check (numerohospedes > 0),
  adultos integer not null default 1 check (adultos >= 0),
  criancas integer not null default 0 check (criancas >= 0),

  -- Pagamento conferido manualmente pelo administrador
  forma_pagamento text check (forma_pagamento is null or forma_pagamento in ('PIX', 'VOUCHER')),
  valor_sinal numeric(12,2) not null default 0 check (valor_sinal >= 0),
  comprovante_url text,
  pagamento_confirmado_em timestamptz,
  pagamento_confirmado_por integer references public.usuario(usuarioid),

  -- Observações e declaração da FNRH
  alergias_restricoes text,
  solicitacoes_especiais text,
  declaracao_aceita boolean not null default false,
  data_declaracao timestamptz,
  assinatura_url text,

  -- Auditoria básica
  datainclusao timestamptz not null default now(),
  dataoperacao timestamptz not null default now(),
  usuariooperacao integer references public.usuario(usuarioid),
  naturezaoperacao text not null default 'INSERT'
);

create index if not exists cadastro_fnrh_status_idx
  on public.cadastro_fnrh(status);

create index if not exists cadastro_fnrh_cpf_idx
  on public.cadastro_fnrh(cpf);

create index if not exists cadastro_fnrh_hospede_idx
  on public.cadastro_fnrh(hospedeid);

create index if not exists cadastro_fnrh_reserva_idx
  on public.cadastro_fnrh(reservaid);

create table if not exists public.cadastro_fnrh_acompanhante (
  acompanhanteid bigint generated by default as identity primary key,
  cadastroid bigint not null references public.cadastro_fnrh(cadastroid) on delete cascade,
  reservaid integer null references public.reserva(reservaid),

  nomecompleto text not null,
  documento text,
  datanascimento date,
  menoridade boolean not null default false,
  cpfresponsavel text,
  autorizacao_url text,
  autorizacao_validada boolean not null default false,
  observacoes text,
  datainclusao timestamptz not null default now()
);

create index if not exists cadastro_fnrh_acompanhante_cadastro_idx
  on public.cadastro_fnrh_acompanhante(cadastroid);

create index if not exists cadastro_fnrh_acompanhante_reserva_idx
  on public.cadastro_fnrh_acompanhante(reservaid);

-- Regras da aplicação:
--
-- Confirmação manual pelo administrador:
-- update public.cadastro_fnrh
-- set status = 'LIBERADA_PARA_RESERVA',
--     pagamento_confirmado_em = now(),
--     pagamento_confirmado_por = :usuario_admin,
--     dataoperacao = now(),
--     naturezaoperacao = 'UPDATE'
-- where cadastroid = :cadastroid
--   and status = 'AGUARDANDO_PAGAMENTO';
--
-- Nesse mesmo fluxo, a aplicação deve criar/atualizar o titular em public.hospede
-- e salvar o hospedeid no cadastro_fnrh.
-- Também deve copiar para hospede:
-- rg, passaporte, datanascimento, nacionalidade, sexo, telefone, email,
-- endereco, cidade, estado, cep, profissao, proximodestino,
-- ultimaprocedencia, cpfresponsavelmenor, alergias_restricoes,
-- solicitacoes_especiais, declaracao_aceita, data_declaracao e assinatura_url.
--
-- Depois que a atendente criar a reserva, os pagamentos e os dados da reserva
-- seguem o fluxo normal já existente no sistema. Depois disso, os acompanhantes
-- devem receber o reservaid.
-- update public.cadastro_fnrh
-- set status = 'RESERVA_CRIADA', reservaid = :reservaid,
--     dataoperacao = now(), naturezaoperacao = 'UPDATE'
-- where cadastroid = :cadastroid
--   and status = 'LIBERADA_PARA_RESERVA';
--
-- Para cancelar:
-- update public.cadastro_fnrh
-- set status = 'CANCELADA', dataoperacao = now(), naturezaoperacao = 'UPDATE'
-- where cadastroid = :cadastroid
--   and status in ('AGUARDANDO_PAGAMENTO', 'LIBERADA_PARA_RESERVA');
--
-- O cliente deve receber somente um link/token para preencher o próprio cadastro.
-- Não conceda acesso geral às tabelas cadastro_fnrh ou hospede para o cliente.
